### ISSUE TITLE
should dynamically generate links on student repos

### ISSUE THREAD

**Issue by Kyche** [certify/template-everyone#15]
When the repo is cloned(?) to a student's account, the links in the readme still link to instructions back here. Following those instructions verbatim may lead to confusion, such as being unable to assign oneself an issue. Admittedly I'm embarrassed I got stumped by this.

Ideal behavior will link from the main readme to the corresponding document on the students repo.

**Comment by Kyche** [comment]
Nevermind, it looks like I got an older version of the readme.

**Comment by PeterBell** [comment]
Hi @Kyche thanks so much for the feedback. You did indeed get an old version of the README - should be resolved shortly - sorry for any inconvenience! cc @johnpaulashenfelter
