### ISSUE TITLE
Fix Internet Explorer and Safari formatting

### ISSUE THREAD

**Issue by crichID** [certify/template-everyone#2]
We need to fix the position of the photo in relation to the individual bio in both IE and Safari.

**Comment by PeterBell** [comment]
I think *Microsoft* needs to fix internet explorer. But I do agree that we should make this look OK in IE9+ as we have a bunch of corporate users.

**Comment by sanspace** [comment]
I'm not sure what should be done about this. :confused:

**Comment by israelvicars** [comment]
@crichID Can you confirm if this issue is intended for students of the Github Training project? I think that's what @sanspace is referring to as well. It's showing as the second issue after, "Class Goals".

**Comment by crichID** [comment]
@sanspace @israelvicars This issue is used in a later lab in the course, please feel free to disregard this issue until you are instructed to reference it specifically!

**Comment by israelvicars** [comment]
@crichID Thanks for the clarification, especially the exclamation mark so I know the misunderstanding was my fault! :stuck_out_tongue:

**Comment by crichID** [comment]
@israelvicars I was definitely not trying to imply the mis-understanding was your fault. I have a bad habit of using exclamation marks when I should use :smile:s instead.

**Comment by israelvicars** [comment]
@crichID Sorry for flaring. Not appropriate by me, especially if we haven't met before. Course is really interesting. Thanks for your help.
