### ISSUE TITLE
Things to include in ideal bio

### ISSUE THREAD

**Issue by crichID** [certify/template-everyone#3]
We should all create great bios in this project. Make sure your bio includes:
- [ ] Your name
- [ ] Where you are from
- [ ] A favorite food
- [ ] A hobby

**Comment by jsjain** [comment]
### Shubham Jain
- Goa, India
  *Pizza
  *Reading online
  - about tech stuff
  - cool new gadgets

**Comment by premkumar-masilamani** [comment]
- Premkumar Masilamani
- Bangalore, India
- Any living organism that moves
- Doing nothing (getting better at it everyday)
